
all:

	$(MAKE) cat.test
	$(MAKE) dir.test
	$(MAKE) grep.test
	$(MAKE) rm.test
	$(MAKE) sleep.test
	$(MAKE) which.test
	$(MAKE) dd.test
	$(MAKE) dmesg.test
	$(MAKE) mkdir.test
	$(MAKE) shell.test
	$(MAKE) tar.test
	$(MAKE) dd.test.simple
	$(MAKE) find.test
	$(MAKE) mount.test
	$(MAKE) showip.test
	$(MAKE) umount.test

clean:
	$(RM) cat.test        
	$(RM) dir.test    
	$(RM) grep.test   
	$(RM) rm.test      
	$(RM) sleep.test   
	$(RM) which.test
	$(RM) dd.test         
	$(RM) dmesg.test  
	$(RM) mkdir.test 
	$(RM) shell.test   
	$(RM) tar.test
	$(RM) dd.test.simple  
	$(RM) find.test   
	$(RM) mount.test 
	$(RM) showip.test  
	$(RM) umount.test


