
all:

	$(MAKE) longtest        
	$(MAKE) sh.testdeep  
	$(MAKE) sh.tests1  
	$(MAKE) sh.tests3  
	$(MAKE) sh.tests5  
	$(MAKE) sh.tests
	$(MAKE) sh.boolean.test  
	$(MAKE) sh.tests10   
	$(MAKE) sh.tests2  
	$(MAKE) sh.tests4
	$(MAKE) sh.tests7
	$(MAKE) -o stdcat stdcat.c

clean:
	$(RM) longtest
	$(RM) sh.testdeep
	$(RM) sh.tests1
	$(RM) sh.tests3
	$(RM) sh.tests5
	$(RM) sh.tests
	$(RM) sh.boolean.test
	$(RM) sh.tests10
	$(RM) sh.tests2
	$(RM) sh.tests4
	$(RM) sh.tests7
	$(RM) stdcat

