# graff-dwm ( rewrite of: dwm - dynamic window manager)
# See LICENSE file for copyright and license details.  

CFLAGS += -std=c99 -Wall -Wextra 
LDFLAGS += -lX11 -lc

CC = cc

all: 	graff-dwm 

clean:
	rm -f graff-dwm



