#!/bin/sh

# Use `buildroot' to make a uclibc based micro sized
# root filesystem, which is complete with xorg.


git clone git://git.buildroot.net/buildroot

cd buildroot 

cat > configs/my_defconfig << EOF
BR2_PREFER_STATIC_LIB=y
BR2_x86_64=y
BR2_CCACHE=y
BR2_TARGET_ROOTFS_CPIO=y
BR2_JLEVEL=$(($(grep -c ^processor /proc/cpuinfo)*2))
BR2_DL_DIR="/home/$USER/.bldroot"
BR2_TOOLCHAIN_BUILDROOT_LARGEFILE=y
BR2_TOOLCHAIN_BUILDROOT_INET_IPV6=y
BR2_TOOLCHAIN_BUILDROOT_WCHAR=y
BR2_TOOLCHAIN_BUILDROOT_CXX=y 
BR2_TOOLCHAIN_BUILDROOT_INET_RPC=y
BR2_TOOLCHAIN_BUILDROOT_LOCALE=y
BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_UDEV=y
BR2_TARGET_GENERIC_GETTY_PORT="tty1" 
BR2_PACKAGE_XORG7=y
BR2_PACKAGE_XAPP_TWM=y
BR2_PACKAGE_XAPP_SETXKBMAP=y
BR2_PACKAGE_XAPP_XINIT=y
BR2_PACKAGE_XAPP_XINPUT=y
BR2_PACKAGE_XSERVER_XORG_SERVER=y
BR2_PACKAGE_XSERVER_XORG_SERVER_MODULAR=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_EVDEV=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_KEYBOARD=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_MOUSE=y
BR2_PACKAGE_XDRIVER_XF86_VIDEO_CIRRUS=y
BR2_PACKAGE_XDRIVER_XF86_VIDEO_FBDEV=y
BR2_PACKAGE_XDRIVER_XF86_VIDEO_VESA=y
BR2_PACKAGE_LIBERATION=y
BR2_PACKAGE_BLACKBOX=y
BR2_PACKAGE_XTERM=y
BR2_PACKAGE_MAKEDEVS=y
BR2_PACKAGE_NCURSES_TARGET_PANEL=y
BR2_PACKAGE_NCURSES_TARGET_FORM=y
BR2_PACKAGE_NCURSES_TARGET_MENU=y
BR2_PACKAGE_ALSA_UTILS=y 
EOF

make my_defconfig

make

kvm -m 500 \
-kernel output/images/bzImage\
-initrd output/images/rootfs.cpio

# 2014 (C) Documentation script, Statix, cgraf 
